### ISSUE TITLE
ERROR: Cannot access *.f *.f90 etc files while installing ACX package in ubuntu 20.04

### ISSUE THREAD

**Issue by Abhijeet-star** [AtomDB/acx#1]
Hello,

I am trying to install the acx model (https://github.com/AtomDB/acx/releases/tag/v1.0.3) as per the manual - https://github.com/AtomDB/acx/blob/9e70b847f4f9ce1c7cd0fe90a96f2ac51668b019/doc/manual.pdf

However, after using the second compilation method described, I am getting the following error. (The first method did not work)

(base) user@user-pc:~$ heainit
(base) user@user-pc:~$ cd /home/abhijeet/acx-1.0.3/xspec
(base) user@user-pc:~/acx-1.0.3/xspec$ cp acx.h.in acx.h

(I edited the acx.h file as given in the manual)

(base) user@user-pc:~/acx-1.0.3/xspec$ initpackage acx model.dat .

 The following files will be created in directory: /home/abhijeet/acx-1.0.3/xspec:

 acxFunctionMap.h  	header specification file for functions
 acxFunctionMap.cxx	function adding model functions/subroutines
 acx.cxx           	initializer function called by command interpreter
                    	on loading of package

Gathering information from model initialization file: /home/abhijeet/acx-1.0.3/xspec/model.dat...

Model name: acx       No. of params: 6     Emin:     0.00e+00  Emax:     1.00e+20  f():  acxfunc  Type: add
Model name:     vacx  No. of params:   17  Emin:     0.00e+00  Emax:     1.00e+20  f(): vacxfunc  Type: add
Model name:   acxion  No. of params:    5  Emin:     0.00e+00  Emax:     1.00e+20  f():   acxion  Type: add
... done
   3  Additive models
   0  Multiplicative models
   0  Convolution models
   0  Mixing models
   0  Pile-up models
   0  Mixing pile-up models found altogether.

Writing Initializer Code for package: acx...done
Writing Makefile for package...
/bin/ls: cannot access '*.f': No such file or directory
/bin/ls: cannot access '*.f90': No such file or directory
/bin/ls: cannot access '*.f03': No such file or directory
/bin/ls: cannot access '*.c': No such file or directory
/bin/ls: cannot access '*.cpp': No such file or directory
/bin/ls: cannot access '*.C': No such file or directory
/bin/ls: cannot access '*.cc': No such file or directory
...done
Writing pkgIndex.tcl file...
...done

Can someone please tell how to solve this issue?

Thanks..

**Comment by jagophile** [comment]
Hi,

I have looked into this, and although them messages look worrying, they aren't actually errors in the compilation and can be ignored. If you continue on to the next step
(base) user@user-pc:$ hmake

and then load the model into xspec:
XSPEC> lmod acx /path/to/acx-1.0.3/xspec

Then it should work without further errors.

Please let me know if this doesn't work

**Comment by Abhijeet-star** [comment]
Hello,

Thanks for the reply. Yes! It did work!

**Comment by jagophile** [comment]
Hi, 

I will look into this on Tuesday (holiday weekend here). Can you tell we what version of HEASOFT you are using?

Thanks, 
Adam

⁣Sent from TypeApp ​

**Comment by Abhijeet-star** [comment]
Hi,

The problem is sorted as I have installed a new version of Heasoft in
Ubuntu 22.04.
Thank you for your support and cooperation.

Best regards
Abhijeet
